application: mewert-langmap
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: "2.6"

handlers:
- url: /
  script: helloworld.application

- url: /map
  upload: static/index.html
  static_files: static/index.html

#- url: /data.json
#  upload: data.json
#  static_files: data.json

- url: /.*/.*/data.json
  script: helloworld.application

- url: /sheets
  script: helloworld.application

- url: /
  static_dir: static/
